// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTrqlUz3rGh8_RtpyTd9LcRTvjNjjXjuM',
    appId: '1:711004115285:web:522c7469e83e29ecbadfdc',
    messagingSenderId: '711004115285',
    projectId: 'aaya-user',
    authDomain: 'aaya-user.firebaseapp.com',
    storageBucket: 'aaya-user.appspot.com',
    measurementId: 'G-11NJKEC491',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJpwDmj_5kTB8MhtkCv_rxu_5qibuw8gU',
    appId: '1:711004115285:android:11979d0dcf2cd63cbadfdc',
    messagingSenderId: '711004115285',
    projectId: 'aaya-user',
    storageBucket: 'aaya-user.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVoFZnKqmI4v2SkplZBJzisCUwSC3SGyk',
    appId: '1:711004115285:ios:77de1e0e6322fa90badfdc',
    messagingSenderId: '711004115285',
    projectId: 'aaya-user',
    storageBucket: 'aaya-user.appspot.com',
    iosBundleId: 'com.aaya.aayauser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVoFZnKqmI4v2SkplZBJzisCUwSC3SGyk',
    appId: '1:711004115285:ios:3f5563532ac70b9abadfdc',
    messagingSenderId: '711004115285',
    projectId: 'aaya-user',
    storageBucket: 'aaya-user.appspot.com',
    iosBundleId: 'com.aaya.aayauser.RunnerTests',
  );
}
